[package]
name = "danube-parse"
version = "0.1.0"
authors = ["Danuel <public.danuel@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.2"
nom_locate = "2.0.0"
danube-lex = { path = "../danube-lex" }
